// <auto-generated />
namespace ReportesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class estado_fallaReportes_conexion2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estado_fallaReportes_conexion2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151956054_estado_fallaReportes_conexion2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
