// <auto-generated />
namespace ReportesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lat_and_long_todecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lat_and_long_todecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150825083_lat_and_long_todecimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
